move oauth to handler
Kelompok-4-Capstone-Alterra/go_women_center pull request #1
Opened 2023-05-24 06:31 UTC by ThiccPan

2023-05-24 06:56 UTC, Ganes556 commented on user/handler/http_user_handler.go
nanti klo ada middleware khusus buat user ini tetep di taruh di  path root/middleware ya?

2023-05-24 07:17 UTC, Ganes556 commented on user/handler/http_user_handler.go
test

2023-05-24 07:19 UTC, ThiccPan commented on user/handler/http_user_handler.go
bisa sih, klo nggak taro di dalem handlernya, bikin folder middleware di situ

2023-05-24 07:23 UTC, Ganes556 commented on user/handler/http_user_handler.go
ok dh, atau engga klo middlewarenya mau dipake buat semua handler baru buat di root path, klo gk di tiap domainnya aja. trus untuk folder repository itu bakal kek gini kah, user/repository/orm_gorm_mysql.go?

2023-05-24 08:10 UTC, ThiccPan commented on user/handler/http_user_handler.go
iya bg, kasih penamaan domainnya jg di repositorynya, gorm_mysql_user.go

2023-05-24 08:19 UTC, Ganes556 approved these changes

2023-05-24 08:40 UTC, Ganes556 requested changes

2023-05-24 08:40 UTC, Ganes556 commented on user/handler/http_user_handler.go
> +func (u *userHandler) LoginHandler(e echo.Context) error {
keknya lebih baik u ganti jadi h (handler) trus e jadi c (context), gtu juga sama yang lainnya kek repo nanti jadi r doang

2023-05-24 14:23 UTC, Saident approved these changes

2023-05-25 07:17 UTC, ardin2001 approved these changes

2023-05-25 07:22 UTC, merged