Feature/report
Kelompok-4-Capstone-Alterra/go_women_center pull request #82
Opened 2023-06-20 20:40 UTC by ThiccPan

feature: 
- get all report
- download report

2023-06-20 22:24 UTC, ardin2001 approved these changes

2023-06-20 23:33 UTC, Ganes556 requested changes

2023-06-20 23:33 UTC, Ganes556 commented on app/main.go
> +	// sslconf := config.SSLconf{
aktifin sslnya

2023-06-21 02:27 UTC, Saident approved these changes
kek kata bang ganes, sslnya bang jangan lupa

2023-06-21 05:50 UTC, ThiccPan commented on app/main.go
> +	// sslconf := config.SSLconf{
woke fixed bang

2023-06-21 06:04 UTC, Ganes556 approved these changes

2023-06-21 06:12 UTC, merged